privileges:
    PRIV_SPORTABZEICHEN_RESULTS:
        label: "Sportabzeichen: Ergebnisse eintragen"
        description: "Berechtigt das Eintragen von Sportabzeichen-Leistungen."

    PRIV_SPORTABZEICHEN_MANAGE_PARTICIPANTS:
        label: "Sportabzeichen: Teilnehmer verwalten"
        description: "Darf Teilnehmer anlegen, bearbeiten und Prüfungen zuordnen."

    PRIV_SPORTABZEICHEN_REQUIREMENTS:
        label: "Sportabzeichen: Anforderungen verwalten"
        description: "Darf Anforderungen importieren, CSV hochladen und bearbeiten."

    PRIV_SPORTABZEICHEN_VIEW_OWN:
            label: "Sportabzeichen: Eigene Ergebnisse einsehen"
            description: "Erlaubt dem Benutzer, seine eigenen Sportabzeichen-Anforderungen und Ergebnisse einzusehen."